package cn.tongdun.mobrisk.core.tools

/**
 * @description: Constants
 * @author: wuzuchang
 * @date: 2023/5/12
 */
object Constants {
    const val KEY_DEVICE_ID = "device_id"
    const val KEY_DEVICE_RISK_LABEL = "device_risk_label"
    const val KEY_DEVICE_DETAIL = "device_detail"
    const val KEY_ANDROID_ID = "androidId"
    const val KEY_GSF_ID = "gsfId"
    const val KEY_MEDIA_DRM_ID = "mediaDrmId"
    const val KEY_VB_META_DIGEST = "vbMetaDigest"
    const val KEY_MODEL = "model"
    const val KEY_MANUFACTURER = "manufacturer"
    const val KEY_ANDROID_VERSION = "androidVersion"
    const val KEY_SDK_VERSION = "sdkVersion"
    const val KEY_KERNEL_VERSION = "kernelVersion"
    const val KEY_FINGERPRINT = "fingerprint"
    const val KEY_HARDWARE = "HARDWARE"
    const val KEY_DISPLAY = "display"
    const val KEY_HOST = "host"
    const val KEY_BRAND = "brand"
    const val KEY_PRODUCT = "product"
    const val KEY_BATTERY_HEALTH_STATUS = "batteryHealthStatus"
    const val KEY_BATTERY_STATUS = "batteryStatus"
    const val KEY_BATTERY_LEVEL = "batteryLevel"
    const val KEY_BATTERY_TEMP = "batteryTemp"
    const val KEY_BATTERY_TOTAL_CAPACITY = "batteryTotalCapacity"
    const val KEY_CPU_PROCESSOR = "cpuProcessor"
    const val KEY_CPU_HARDWARE = "cpuHardware"
    const val KEY_CORES_COUNT = "coresCount"
    const val KEY_ABI_TYPE = "abiType"
    const val KEY_DEBUG = "debug"
    const val KEY_MULTIPLE = "multiple"
    const val KEY_ROOT = "root"
    const val KEY_XPOSED = "xposed"
    const val KEY_MAGISK = "magisk"
    const val KEY_EMULATOR = "emulator"
    const val KEY_HOOK = "hook"
    const val KEY_COUNTRY = "country"
    const val KEY_LANGUAGE = "language"
    const val KEY_TIMEZONE = "timezone"
    const val KEY_TOTAL_MEMORY = "totalMemory"
    const val KEY_AVAILABLE_MEMORY = "availableMemory"
    const val KEY_TOTAL_STORAGE = "totalStorage"
    const val KEY_AVAILABLE_STORAGE = "availableStorage"
    const val KEY_APP_LIST = "appList"
    const val KEY_SYSTEM_APP_LIST = "systemAppList"
    const val KEY_SENSORS_INFO = "sensorsInfo"
    const val KEY_ADB_ENABLED = "adbEnabled"
    const val KEY_DEVELOPMENT_SETTING_ENABLED = "developmentSettingEnabled"
    const val KEY_HTTP_PROXY = "httpProxy"
    const val KEY_DATA_ROAMING = "dataRoaming"
    const val KEY_ALLOW_MOCK_LOCATION = "allowMockLocation"
    const val KEY_ACCESSIBILITY_ENABLED = "accessibilityEnabled"
    const val KEY_DEFAULT_INPUTMETHOD = "defaultInputMethod"
    const val KEY_TOUCH_EXPLORATION_ENABLED = "touchExplorationEnabled"
    const val KEY_SCREEN_BRIGHTNESS = "screenBrightness"
    const val KEY_SCREEN_OFF_TIMEOUT = "screenOffTimeout"
    const val KEY_SCREEN_RESOLUTION = "screenResolution"
    const val KEY_SCREEN_INCHES = "screenInches"
    const val KEY_FILES_ABSOLUTE_PATH = "filesAbsolutePath"
    const val KEY_PACKAGE_NAME = "packageName"

    //magisk related files
    const val MAGISK_MOUNTS_PATH = "/proc/self/mounts"
    const val MAGISK_MOUNT_INFO_PATH = "/proc/self/mountinfo"
    const val MAGISK_MOUNT_STATS_PATH = "/proc/self/mountstats"
}