name: Android CI

on:
  push:
    branches: [ "main" ]
    tag:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build library
      run: ./gradlew trustdevice:assembleRelease

    - name: Save library to artifacts
      uses: actions/upload-artifact@v2
      with:
        path: trustdevice/build/outputs/aar/*

    - name: Build App
      run: ./gradlew app:assembleRelease

    - name: Save application to artifacts
      uses: actions/upload-artifact@v2
      with:
        path: app/build/outputs/apk/release/*
